# core/challenges.py
#
# Withdrawal confirmation challenges — a second-channel confirmation for
# external-application withdrawals (e.g. Meridian sell/payout).
#
# Flow:
#   1. The external app (scope 'burn') requests a challenge for an account,
#      referencing its own order id (external_ref). We generate a 6-digit code,
#      store ONLY its salted hash, and return an id.
#   2. The account owner sees the pending challenge in the System A dashboard and
#      approves ("this is me") — which reveals the code to the owner — or denies.
#   3. The owner types the code into the external app; the app calls verify().
#      We compare hashes; on success status -> 'confirmed' (one-time).
#
# Security:
#   • Code lives only as a salted SHA-256 hash (HMAC with the admin secret) —
#     a 6-digit code is low entropy, so the salt stops offline rainbow lookups.
#   • Short TTL, single active challenge per (account, external_ref), limited
#     attempts, one-time confirmation. The code is generated by System A (the
#     trusted side); the external app can only verify, never mint.

import hashlib
import hmac
import os
import secrets
from datetime import datetime, timedelta, timezone

from . import db

TTL_SECONDS = int(os.getenv("WITHDRAWAL_CHALLENGE_TTL_S", "300"))  # 5 min
MAX_ATTEMPTS = int(os.getenv("WITHDRAWAL_CHALLENGE_MAX_ATTEMPTS", "5"))
_SALT = os.getenv("ADMIN_API_KEY", "") or os.getenv("DB_PASSWORD", "") or "salt"


def _hash_code(code: str) -> str:
    # HMAC-SHA256 with the server secret as key: salted so a DB leak can't be
    # brute-forced offline against the tiny 6-digit space without the secret.
    return hmac.new(_SALT.encode("utf-8"), code.encode("utf-8"), hashlib.sha256).hexdigest()


def _gen_code() -> str:
    # 6 digits, cryptographically random (000000–999999).
    return f"{secrets.randbelow(1_000_000):06d}"


def request_challenge(account_name: str, external_ref: str, app_name: str, amount):
    """Create (or replace) a pending challenge. Returns {id, expires_at}. The
    plaintext code is NOT returned here — only the owner reveals it via approve."""
    code = _gen_code()
    code_hash = _hash_code(code)
    expires = datetime.now(timezone.utc) + timedelta(seconds=TTL_SECONDS)
    with db.get_cursor() as cur:
        # One active challenge per (account, external_ref): upsert.
        cur.execute(
            """
            INSERT INTO withdrawal_challenges
                (account_name, external_ref, app_name, code_hash, amount, status, attempts, expires_at)
            VALUES (%s,%s,%s,%s,%s,'pending',0,%s)
            ON CONFLICT (account_name, external_ref) DO UPDATE SET
                app_name=EXCLUDED.app_name, code_hash=EXCLUDED.code_hash,
                amount=EXCLUDED.amount, status='pending', attempts=0,
                created_at=NOW(), expires_at=EXCLUDED.expires_at
            RETURNING id
            """,
            (account_name, external_ref, app_name, code_hash, amount, expires),
        )
        row = cur.fetchone()
    # Stash the plaintext ONLY in memory for the immediate caller path is not
    # needed; the owner reveals it via approve(). Return the id.
    return {"id": row[0], "expires_at": expires.isoformat()}


def list_pending(account_name: str):
    """Pending challenges for an account (for the owner's dashboard)."""
    with db.get_cursor() as cur:
        cur.execute(
            """
            SELECT id, external_ref, app_name, amount, status, created_at, expires_at
            FROM withdrawal_challenges
            WHERE account_name=%s AND status='pending' AND expires_at > NOW()
            ORDER BY created_at DESC
            """,
            (account_name,),
        )
        rows = cur.fetchall()
    return [
        {
            "id": r[0],
            "external_ref": r[1],
            "app_name": r[2],
            "amount": str(r[3]) if r[3] is not None else None,
            "status": r[4],
            "created_at": r[5].isoformat() if r[5] else None,
            "expires_at": r[6].isoformat() if r[6] else None,
        }
        for r in rows
    ]


def approve(account_name: str, challenge_id: int):
    """Owner approves ('this is me'): regenerate a fresh code, mark approved,
    and RETURN the plaintext code to show the owner once. Regenerating on
    approve means the code only exists after explicit owner consent."""
    code = _gen_code()
    code_hash = _hash_code(code)
    expires = datetime.now(timezone.utc) + timedelta(seconds=TTL_SECONDS)
    with db.get_cursor() as cur:
        cur.execute(
            """
            UPDATE withdrawal_challenges
            SET status='approved', code_hash=%s, attempts=0, expires_at=%s
            WHERE id=%s AND account_name=%s AND status='pending' AND expires_at > NOW()
            RETURNING id
            """,
            (code_hash, expires, challenge_id, account_name),
        )
        ok = cur.fetchone() is not None
    if not ok:
        return None
    return {"code": code, "expires_at": expires.isoformat()}


def deny(account_name: str, challenge_id: int) -> bool:
    """Owner denies ('not me'): the challenge can never be confirmed."""
    with db.get_cursor() as cur:
        cur.execute(
            "UPDATE withdrawal_challenges SET status='denied' "
            "WHERE id=%s AND account_name=%s AND status IN ('pending','approved') RETURNING id",
            (challenge_id, account_name),
        )
        return cur.fetchone() is not None


def verify(account_name: str, external_ref: str, code: str, amount=None):
    """Called by the external app with the code the owner typed in.
    Returns 'confirmed' on success; otherwise an error reason string.

    When `amount` is supplied, it MUST equal the amount the challenge was created
    for — a confirmation approved for one amount can never authorise a
    different-amount withdrawal (binds code ↔ order ↔ amount)."""
    with db.get_cursor() as cur:
        cur.execute(
            """
            SELECT id, code_hash, status, attempts, expires_at, amount
            FROM withdrawal_challenges
            WHERE account_name=%s AND external_ref=%s
            FOR UPDATE
            """, 
            (account_name, external_ref),
        )
        row = cur.fetchone()
        if row is None:
            return "not_found"
        cid, code_hash, status, attempts, expires_at, stored_amount = row
        # Amount binding: reject if the caller declares an amount that does not
        # match what the owner approved. Checked BEFORE any success path.
        if amount is not None and stored_amount is not None:
            if int(amount) != int(stored_amount):
                return "amount_mismatch"
        if status == "confirmed":
            return "confirmed"  # idempotent success
        if status == "denied":
            return "denied"
        if status != "approved":
            return "not_approved"  # owner hasn't approved in the dashboard yet
        if expires_at <= datetime.now(timezone.utc):
            cur.execute("UPDATE withdrawal_challenges SET status='expired' WHERE id=%s", (cid,))
            return "expired"
        if attempts >= MAX_ATTEMPTS:
            cur.execute("UPDATE withdrawal_challenges SET status='denied' WHERE id=%s", (cid,))
            return "too_many_attempts"
        if hmac.compare_digest(code_hash, _hash_code(str(code))):
            cur.execute("UPDATE withdrawal_challenges SET status='confirmed' WHERE id=%s", (cid,))
            return "confirmed"
        cur.execute("UPDATE withdrawal_challenges SET attempts=attempts+1 WHERE id=%s", (cid,))
        return "invalid_code"


def expired_unnotified(account_name: str):
    """Sweep stale pending challenges to 'expired', then return the ones that
    expired WITHOUT being approved and have not yet been shown to the owner.
    Each is returned once (we stamp notified_at). This powers the dashboard
    "a withdrawal request expired while you were away" notice."""
    with db.get_cursor() as cur:
        # 1) Move any pending challenges past their expiry into 'expired'.
        cur.execute(
            "UPDATE withdrawal_challenges SET status='expired' "
            "WHERE account_name=%s AND status='pending' AND expires_at <= NOW()",
            (account_name,),
        )
        # 2) Fetch expired-and-unnotified for this account.
        cur.execute(
            """
            SELECT id, external_ref, app_name, amount, expires_at
            FROM withdrawal_challenges
            WHERE account_name=%s AND status='expired' AND notified_at IS NULL
            ORDER BY expires_at DESC
            LIMIT 20
            """,
            (account_name,),
        )
        rows = cur.fetchall()
        if rows:
            ids = [r[0] for r in rows]
            cur.execute(
                "UPDATE withdrawal_challenges SET notified_at=NOW() WHERE id = ANY(%s)",
                (ids,),
            )
    return [
        {
            "id": r[0],
            "external_ref": r[1],
            "app_name": r[2],
            "amount": str(r[3]) if r[3] is not None else None,
            "expired_at": r[4].isoformat() if r[4] else None,
        }
        for r in rows
    ]
